# Exercise 2.A Fundamentals of pandas

In [14]:
import numpy as np
import pandas as pd

 ## Series

In [15]:
aa = [1,2,3,4]
ab = (5,6,7,8)
ac = {9,10,11,12}
ad = {'first': 13, 'second': 14, 'third': 15, 'fourth': 16 }

In [16]:
ser1 = pd.Series(aa)
ser2 = pd.Series(ab)
ser3 = pd.Series(list(ac))
ser4 = pd.Series(ad)

print(ser1)
print(ser2)
print(ser3)
print(ser4)

0    1
1    2
2    3
3    4
dtype: int64
0    5
1    6
2    7
3    8
dtype: int64
0     9
1    10
2    11
3    12
dtype: int64
first     13
second    14
third     15
fourth    16
dtype: int64

In [17]:
ser5 = pd.Series(17, 18, 19, 20)

TypeError: Index(...) must be called with a collection of some kind, 18 was passed

In [ ]:
# this happens when you use numbers and not arrays, and it has 5 values and not 4

## DataFrames from Series

In [ ]:
df1 = pd.DataFrame(ser1)
df1

In [ ]:
df1.insert(1, "ser2", ser2)
df1.insert(2, "ser3", ser3)
df1

In [ ]:
df1.insert(3, "ser4", ser4) # ser4 is different from the others because its a dictanay.
df1

In [ ]:
df1.loc[4] = [5, 9, 12, 0]
df1

 ## Reading Data into a DataFrame

In [ ]:
df2 = pd.read_csv('sakila_example.csv')
df2

In [ ]:
df2.head()

In [ ]:
df2.tail(10)

In [ ]:
df2.info()

i can see that the data types are all object types. It also take up 10.4kb of storage.

In [ ]:
df2.describe()

some useful insights are seeing how many unique values there are. the summaray this isnt useful is the freq.

In [19]:
df3 = pd.read_csv('northwind_example.csv')
df3

     OrderID                    ProductName  UnitPrice  Quantity
0      10248                 Queso Cabrales       14.0        12
1      10248  Singaporean Hokkien Fried Mee        9.8        10
2      10248         Mozzarella di Giovanni       34.8         5
3      10249          Manjimup Dried Apples       42.4        40
4      10249                           Tofu       18.6         9
..       ...                            ...        ...       ...
495    10435         Mozzarella di Giovanni       27.8        10
496    10436         Gnocchi di nonna Alice       30.4        40
497    10436       Wimmers gute Semmelkndel       26.6        30
498    10436             Rhnbru Klosterbier        6.2        24
499    10436                      Spegesild        9.6         5

[500 rows x 4 columns]

In [20]:
df3.describe()

            OrderID   UnitPrice    Quantity
count    500.000000  500.000000  500.000000
mean   10341.364000   23.371400   24.330000
std       54.442663   27.334436   18.069702
min    10248.000000    2.000000    1.000000
25%    10294.000000   10.400000   10.000000
50%    10341.000000   15.800000   20.000000
75%    10389.000000   27.800000   32.000000
max    10436.000000  210.800000  120.000000

the summaray shows the count,mean, min and max of the data. this is differnet than before because there are a lot more intger values.

 ## Coding a DataFrame

In [21]:
test_data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8],  
    'Name': ['Alicia', 'Bob', 'Charlie', 'Dominic', 'Eve', 'Frank', 'Grace', 'Heidi'],  
    'Age': [25, np.nan, 22, 19, 31, 35, np.nan, 18],  
    'City': ['NY', 'LA', 'Chicago', 'Houston', 'Phoenix', 'Boston', 'Austin', 'San Diego'],  
    'Score': [85, 92, -1, 65, 78, np.nan, 55, 90]}

In [23]:
df4 =  pd.DataFrame(test_data)
df4

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [24]:
df4.to_csv('test_data.csv', index=False)